export const basic: IComponents = {
  root: {
    id: 'root',
    parent: 'root',
    type: 'Button',
    children: [
      'comp-KABHO0OMD9L4Y',
      'comp-KABL73JKJ3346',
      'comp-KABLTNBL0DYWN',
      'comp-KAEEWND2G5ZWC',
      'comp-KAEEY1LMYOEBB',
      'comp-KAEFVQB00H1XF',
      'comp-KAEG1FOWLT9EH',
      'comp-KAEG1GWHXZBO2',
      'comp-KAEGPSG72ZUAI',
      'comp-KAEHR69OFGUBN',
      'comp-KAEHRSNDT78JT',
    ],
    props: {},
  },
  'comp-KABHO0OMD9L4Y': {
    id: 'comp-KABHO0OMD9L4Y',
    props: { children: 'asdasd' },
    children: ['comp-KABHO3961PXTR'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KABHO3961PXTR': {
    id: 'comp-KABHO3961PXTR',
    props: { children: 'Tag name', colors: { background: '#01A77B' } },
    children: [],
    type: 'Tag',
    parent: 'comp-KABHO0OMD9L4Y',
    rootParentType: 'Tag',
  },
  'comp-KABL73JKJ3346': {
    id: 'comp-KABL73JKJ3346',
    props: {
      margin: '10px',
      padding: '10px',
      backgroundColor: '#da1717',
      height: '100px',
      border: '2px',
      opacity: 1,
    },
    children: ['comp-KABL7EG7CEWYA'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KABL7EG7CEWYA': {
    id: 'comp-KABL7EG7CEWYA',
    props: { label: 'InputText' },
    children: [],
    type: 'InputText',
    parent: 'comp-KABL73JKJ3346',
    rootParentType: 'InputText',
  },
  'comp-KABLTNBL0DYWN': {
    id: 'comp-KABLTNBL0DYWN',
    props: { display: 'block', ml: '', m: '', height: '', padding: '2rem' },
    children: ['comp-KABV6CCAIA8ZV'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KABV6CCAIA8ZV': {
    id: 'comp-KABV6CCAIA8ZV',
    props: { value: 10, currency: 'ARS' },
    children: [],
    type: 'Currency',
    parent: 'comp-KABLTNBL0DYWN',
    rootParentType: 'Currency',
  },
  'comp-KAEEWND2G5ZWC': {
    id: 'comp-KAEEWND2G5ZWC',
    props: { children: 'asdasd', colors: { background: '#01A77B' } },
    children: [],
    type: 'Tag',
    parent: 'root',
    rootParentType: 'Tag',
  },
  'comp-KAEEY1LMYOEBB': {
    id: 'comp-KAEEY1LMYOEBB',
    props: { children: 'dfsdfsdfsdf', size: 'bold', weight: '400' },
    children: [],
    type: 'H1',
    parent: 'root',
    rootParentType: 'H1',
  },
  'comp-KAEFVQB00H1XF': {
    id: 'comp-KAEFVQB00H1XF',
    props: { children: 'Label title', weight: '500' },
    children: [],
    type: 'Label',
    parent: 'root',
    rootParentType: 'Label',
  },
  'comp-KAEG1FOWLT9EH': {
    id: 'comp-KAEG1FOWLT9EH',
    props: { children: 'Heading title' },
    children: [],
    type: 'H1',
    parent: 'root',
    rootParentType: 'H1',
  },
  'comp-KAEG1GWHXZBO2': {
    id: 'comp-KAEG1GWHXZBO2',
    props: { children: 'Heading title', weight: 'bold' },
    children: [],
    type: 'H2',
    parent: 'root',
    rootParentType: 'H2',
  },
  'comp-KAEGPSG72ZUAI': {
    id: 'comp-KAEGPSG72ZUAI',
    props: {},
    children: ['comp-KAEHS9K8RPVLD'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KAEHR69OFGUBN': {
    id: 'comp-KAEHR69OFGUBN',
    props: { label: 'Label Switch', id: 'switch-1', checked: false },
    children: [],
    type: 'Switch',
    parent: 'root',
    rootParentType: 'Switch',
  },
  'comp-KAEHRSNDT78JT': {
    id: 'comp-KAEHRSNDT78JT',
    props: { marginLeft: '100px', backgroundColor: '#58bfb5' },
    children: ['comp-KAEHTO4UXLW24'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KAEHS9K8RPVLD': {
    id: 'comp-KAEHS9K8RPVLD',
    props: { children: 'Heading title' },
    children: [],
    type: 'H3',
    parent: 'comp-KAEGPSG72ZUAI',
    rootParentType: 'H3',
  },
  'comp-KAEHTO4UXLW24': {
    id: 'comp-KAEHTO4UXLW24',
    props: { children: 'Heading title' },
    children: [],
    type: 'Caption',
    parent: 'comp-KAEHRSNDT78JT',
    rootParentType: 'Caption',
  },
}
