export const basic: IComponents = {
  root: {
    id: 'root',
    parent: 'root',
    type: 'Button',
    children: ['comp-KAG7TN6TCGBBS', 'comp-KAG7RSUYZ6KEO'],
    props: { className: 'span-desktop-6' },
  },
  'comp-KAG7Q1OILQBAH': {
    id: 'comp-KAG7Q1OILQBAH',
    props: { columnGap: 0, rowGap: 2 },
    children: [
      'comp-KAG7Q3RN7NDZ7',
      'comp-KAG7R3OVBB04C',
      'comp-KAG7V04K6A7WW',
      'comp-KAG80GFZ4UDER',
      'comp-KAG84CLAZ9IKF',
    ],
    type: 'Grid',
    parent: 'comp-KAG7RSUYZ6KEO',
    rootParentType: 'Grid',
  },
  'comp-KAG7Q3RN7NDZ7': {
    id: 'comp-KAG7Q3RN7NDZ7',
    props: {
      label: 'Nombre',
      placeholder: 'Ingrese su primer nombre',
      className: 'span-desktop-6',
    },
    children: [],
    type: 'InputText',
    parent: 'comp-KAG7Q1OILQBAH',
    rootParentType: 'InputText',
  },
  'comp-KAG7R3OVBB04C': {
    id: 'comp-KAG7R3OVBB04C',
    props: {
      label: 'Apellido',
      placeholder: 'Ingrese su apelido',
      className: 'span-desktop-6',
      size: 'normal',
    },
    children: [],
    type: 'InputText',
    parent: 'comp-KAG7Q1OILQBAH',
    rootParentType: 'InputText',
  },
  'comp-KAG7RSUYZ6KEO': {
    id: 'comp-KAG7RSUYZ6KEO',
    props: {
      width: '50%',
      border: '1px solid blue',
      borderRadius: '9px',
      padding: '1rem',
      backgroundColor: '#dce1e6',
    },
    children: ['comp-KAG7Q1OILQBAH'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KAG7SZUN2GL4V': {
    id: 'comp-KAG7SZUN2GL4V',
    props: { children: 'Ingrese sus datos de contacto', weight: 'bold' },
    children: [],
    type: 'H1',
    parent: 'comp-KAG7TN6TCGBBS',
    rootParentType: 'H1',
  },
  'comp-KAG7TN6TCGBBS': {
    id: 'comp-KAG7TN6TCGBBS',
    props: { marginBottom: '1rem' },
    children: ['comp-KAG7SZUN2GL4V'],
    type: 'Div',
    parent: 'root',
    rootParentType: 'Div',
  },
  'comp-KAG7V04K6A7WW': {
    id: 'comp-KAG7V04K6A7WW',
    props: {
      label: 'Dirección',
      className: 'span-desktop-12',
      placeholder: 'Calle..',
    },
    children: [],
    type: 'InputText',
    parent: 'comp-KAG7Q1OILQBAH',
    rootParentType: 'InputText',
  },
  'comp-KAG80GFZ4UDER': {
    id: 'comp-KAG80GFZ4UDER',
    props: { className: 'span-desktop-12', marginLeft: '', marginTop: '' },
    children: ['comp-KAG80RHK3982M'],
    type: 'Div',
    parent: 'comp-KAG7Q1OILQBAH',
    rootParentType: 'Div',
  },
  'comp-KAG80RHK3982M': {
    id: 'comp-KAG80RHK3982M',
    props: {
      label: 'Compartir mis datos con todos',
      id: 'switch-1',
      checked: false,
    },
    children: [],
    type: 'Switch',
    parent: 'comp-KAG80GFZ4UDER',
    rootParentType: 'Switch',
  },
  'comp-KAG84CLAZ9IKF': {
    id: 'comp-KAG84CLAZ9IKF',
    props: {
      display: 'flex',
      justifyContent: 'flex-end',
      className: 'span-desktop-12',
      alignItems: 'center',
      marginTop: '',
    },
    children: ['comp-KAG84F3J4OJ4L'],
    type: 'Div',
    parent: 'comp-KAG7Q1OILQBAH',
    rootParentType: 'Div',
  },
  'comp-KAG84F3J4OJ4L': {
    id: 'comp-KAG84F3J4OJ4L',
    props: { children: 'Aceptar y destruir', buttonType: 'alert' },
    children: [],
    type: 'Button',
    parent: 'comp-KAG84CLAZ9IKF',
    rootParentType: 'Button',
  },
}
